// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpzYuUrcKozPmY2hw1w7rTA-R43VChF0',
    appId: '1:800722993353:web:982fdcc189a0ad8e7e4d18',
    messagingSenderId: '800722993353',
    projectId: 'registration-5f43a',
    authDomain: 'registration-5f43a.firebaseapp.com',
    storageBucket: 'registration-5f43a.firebasestorage.app',
    measurementId: 'G-DXTT04R3GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdU9GGudpsI2_T3FHd1N4ft1QfHzrBgk',
    appId: '1:800722993353:android:77d9c26430fd4a9f7e4d18',
    messagingSenderId: '800722993353',
    projectId: 'registration-5f43a',
    storageBucket: 'registration-5f43a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF8BZ-fNPMGhh1aWcf5qv2Qy5r1pMC9tk',
    appId: '1:800722993353:ios:20cd012a3bc8a7a07e4d18',
    messagingSenderId: '800722993353',
    projectId: 'registration-5f43a',
    storageBucket: 'registration-5f43a.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF8BZ-fNPMGhh1aWcf5qv2Qy5r1pMC9tk',
    appId: '1:800722993353:ios:20cd012a3bc8a7a07e4d18',
    messagingSenderId: '800722993353',
    projectId: 'registration-5f43a',
    storageBucket: 'registration-5f43a.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDpzYuUrcKozPmY2hw1w7rTA-R43VChF0',
    appId: '1:800722993353:web:0f64c9e95030038d7e4d18',
    messagingSenderId: '800722993353',
    projectId: 'registration-5f43a',
    authDomain: 'registration-5f43a.firebaseapp.com',
    storageBucket: 'registration-5f43a.firebasestorage.app',
    measurementId: 'G-BMDY900DJV',
  );
}
